sonar.projectKey=RentPark
sonar.qualitygate.wait=true

# Kotlin
sonar.coverage.jacoco.xmlReportPaths=RentParkKotlin/app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
sonar.java.binaries=RentParkKotlin/app/build/tmp/kotlin-classes/debug