sonar.projectKey=RentPark
sonar.qualitygate.wait=true

sonar.sources=RentParkKotlin/app/src/main/java
sonar.java.binaries=RentParkKotlin/app/build/tmp/kotlin-classes/debug
sonar.coverage.jacoco.xmlReportPaths=RentParkKotlin/app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
sonar.verbose=true
